### ISSUE TITLE
Localized nightly builds

### ISSUE THREAD

**Issue by ngocanhtve** [LinkSheet/nightly#1]
Although there is a translation for the original. But after I added my locale, there have been no more release builds so far. The nightly builds does not update the translation. Should builds be updated after each translation commit? Helps apps follow the localization process.

After all. Thank for your great app!

**Comment by 1fexd** [comment]
> Although there is a translation for the original. But after I added my locale, there have been no more release builds so far. The nightly builds does not update the translation. Should builds be updated after each translation commit? Helps apps follow the localization process.

Which language are you talking about?

> After all. Thank for your great app!

Thank you!

**Comment by ngocanhtve** [comment]
> Which language are you talking about?

Vietnamese, sir. There is no trace of Vietnamese in the nightly builds, despite the commit from Weblate that Vietnamese is 72% of it has been translated.

**Comment by 1fexd** [comment]
Should be fixed now.
